// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHuimlHmke5SvDGW675JljaS5vJ7wfJAE',
    appId: '1:932333203792:web:405adce62f5ac4c4923c55',
    messagingSenderId: '932333203792',
    projectId: 'lepton-teleop-57d6d',
    authDomain: 'lepton-teleop-57d6d.firebaseapp.com',
    storageBucket: 'lepton-teleop-57d6d.appspot.com',
    measurementId: 'G-TS78KXW4KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3gyttCEGTGGM5ZniwRCZDk0HP6yzcdg4',
    appId: '1:932333203792:android:9050452908c3b607923c55',
    messagingSenderId: '932333203792',
    projectId: 'lepton-teleop-57d6d',
    storageBucket: 'lepton-teleop-57d6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGRAEH8b83kS5xpT1HniWARwCzd6mhBqw',
    appId: '1:932333203792:ios:eb82e82edf15f992923c55',
    messagingSenderId: '932333203792',
    projectId: 'lepton-teleop-57d6d',
    storageBucket: 'lepton-teleop-57d6d.appspot.com',
    iosClientId: '932333203792-a48m80artl6rciavdm2q057cg9eiv4h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.teleOp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGRAEH8b83kS5xpT1HniWARwCzd6mhBqw',
    appId: '1:932333203792:ios:eb82e82edf15f992923c55',
    messagingSenderId: '932333203792',
    projectId: 'lepton-teleop-57d6d',
    storageBucket: 'lepton-teleop-57d6d.appspot.com',
    iosClientId: '932333203792-a48m80artl6rciavdm2q057cg9eiv4h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.teleOp',
  );
}
